---
title: "R Notebook"
output: html_notebook
---

```{r}
library(pacman)
p_load(ggplot2) # Data visualization
p_load(readr) # CSV file I/O, e.g. the read_csv function
p_load(dplyr)
library(multidplyr)
p_load(parallel)
p_load(fasttime)
p_load(xgboost)
p_load(parallel)
p_load(magrittr)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory
#devtools::install_github("hadley/multidplyr")
```

```{r}
source("kaggleUtils.R")
```


```{r}
print(n_cores<-detectCores()-1)
cluster <- create_cluster(n_cores)
print(cluster)
set_default_cluster(cluster)
```

```{r}

myfilename <- "train.csv"
rdsFile <- paste0(myfilename,".RDS")
  
if ( file.exists(rdsFile) ) {
  load(rdsFile, envir=.Glo)
} else {
  train <- read_csv(myfilename, progress=T)
  save(train, file = rdsFile)
} 

nr <- train %>% nrow()
nr
```

```{r}
train %>% head(100)
```

```{r}
train %>% colnames()
```


```{r}
rngIp <- range(train$ip)
rngIp
thrIp <- round(rngIp[2]/4) # 25%
thrIp
```




```{r}
tb <- table(train$is_attributed)
tb
```

```{r}
tb / nr
```


```{r}
click_time_tr <- range(train$click_time)
click_time_tr
```

```{r}
train %<>% filter(ip<thrIp)
```

```{r}
tb <- table(train$is_attributed)
tb
```

```{r}
nrs <- nrow(train)
nrs
tb / nrs
```

```{r}
tr <- partition(train, ip, cluster=cluster)
```

```{r}
rm(train)
```

## TEST

```{r}

myfilename <- "test.csv"
rdsFile <- paste0(myfilename,".RDS")
  
if ( file.exists(rdsFile) ) {
  load(rdsFile)
} else {
  test <- read_csv(myfilename, progress=T)
  save(test, file = rdsFile)
} 


nr <- test %>% nrow()
```

```{r}
test %>% colnames()
```


```{r}
click_time_te <- range(test$click_time)
click_time_te
```


```{r}
click_time_te[2]-click_time_te[1]
```

```{r}
click_time_tr[2]-click_time_te[1]
```


```{r}

tr %<>%   mutate(diff=attributed_time-click_time) 
  # %>% select(-attributed_time, -click_time )
  # group_by(ip, device, os) %>% 
  # mutate(diff_ip_device_os=click_dt-lag(click_dt), cum_att_ip_device_os=cumsum(is_attributed)/1:n() ) %>% 
  # mutate(cum_diff_ip_device_os=cumsum(diff_ip_device_os)/1:n()) %>% 
  # group_by(ip, device) %>% 
  # mutate(diff_ip_device=click_dt-lag(click_dt), cum_att_ip_device=cumsum(is_attributed)/1:n() ) %>% 
  # group_by(ip, os) %>% 
  # mutate(diff_ip_os=click_dt-lag(click_dt), cum_att_ip_os=cumsum(is_attributed)/1:n() ) %>% 
  # group_by(ip) %>% 
  # mutate(diff_ip=click_dt-lag(click_dt), cum_att_ip=cumsum(is_attributed)/1:n() ) %>% 
  # group_by(device) %>% 
  # mutate(diff_device=click_dt-lag(click_dt), cum_att_device=cumsum(is_attributed)/1:n() ) %>% 
  # group_by(os) %>% 
  # mutate(diff_os=click_dt-lag(click_dt), cum_att_os=cumsum(is_attributed)/1:n() )  

#tr_time %>% filter(!is.na(diff_ip_device_os)) %>% head(100)
```

```{r}
ggplot(tr %>% filter(is_attributed==1) %>% collect()) +
  geom_histogram(aes(x=diff), binwidth = 600)  + scale_y_log10() + scale_x_time()
```



```{r}

tr %>%
  group_by(ip) %>% 
  filter( sum(is_attributed) > 1 ) %>% 
  collect() -> trx_df

tr_df %>% 
  filter( is_attributed == 1 ) %>% 
  select(-diff) %>% 
  collect() -> try_df

trx_df %>% 
  inner_join(try_df, by="ip") %>% 
  filter( ( click_time.y < click_time.x & click_time.x <= attributed_time.y ) ) %>% 
  group_by(ip, click_time.y) %>%  
  mutate(n_att=cumsum(is_attributed.x)) %>% 
 # filter(max(n_att)-n_att<2 ) %>% # & click_dt.x!=click_dt.y
  ungroup() -> tr_join

tr_join %>% head(100)

```

```{r}
tr_join %>% 
  group_by(ip, click_time.y) %>% 
  summarise(n=n(), att=sum(is_attributed.x), max_dt=max(click_time.x)-min(click_time.y), min_dt=min(click_time.x)-min(click_time.y)) %>% 
  arrange(-n)  

```

```{r}
tr_join %>% 
  arrange(ip, click_dt.x, click_dt.y) %>%  
  select(ip, is_attributed.x, click_dt.y, click_dt.x, att_dt.y, att_dt.y, app.x, app.y, os.x, os.y, device.x, device.y, channel.x, channel.y)
```


## Feature Engineering

```{r}
tr %>% 
  group_by(ip, device, os) %>% 
  summarise(diff_ip_device_os=click_dt-lag(click_dt), cum_att_ip_device_os=cumsum(is_attributed) ) %>% 
  group_by(ip, device) %>% 
  summarise(diff_ip_device=click_dt-lag(click_dt), cum_att_ip_device=cumsum(is_attributed) ) %>% 
  group_by(ip, os) %>% 
  summarise(diff_ip_os=click_dt-lag(click_dt), cum_att_ip_os=cumsum(is_attributed) ) %>% 
  group_by(ip) %>% 
  summarise(diff_ip=click_dt-lag(click_dt), cum_att_ip=cumsum(is_attributed) ) %>% 
  group_by(device) %>% 
  summarise(diff_device=click_dt-lag(click_dt), cum_att_device=cumsum(is_attributed) ) %>% 
  group_by(os) %>% 
  summarise(diff_os=click_dt-lag(click_dt), cum_att_os=cumsum(is_attributed) )  -> tr_sum
```

```{r}
range(train$click_time)
```

```{r}
table(train$is_attributed)
```


