---
title: "R Notebook"
output: html_notebook
---

```{r}
library(pacman)
p_load(ggplot2) # Data visualization
p_load(readr) # CSV file I/O, e.g. the read_csv function
p_load(dplyr)
library(multidplyr)
p_load(parallel)
p_load(fasttime)
p_load(xgboost)
p_load(parallel)
p_load(magrittr)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory
#devtools::install_github("hadley/multidplyr")
```

```{r}
source("utils_EDA.R")
```

# Load Data

```{r}

load("train.csv.RDS")
#load("test_sup_train.Rds")

```

# join the two datasets

# Feature Engineering

TODO: window of 1hr, 4hr, 12hr, ...

```{r}
train %<>% mutate(id=1:n(), day=format(click_time,"%d"), hour=format(click_time,"%H") )

train %>% head(100)
```


```{r}
# train %>% 
#   group_by(device) %>%
#   mutate(diff_device=as.numeric(click_time-lag(click_time)), 
#          pct_att_device=cumsum(is_attributed)/1:n(), 
#          cps_diff_device = as.numeric(click_time-click_time[1])/1:n() ) %>%
#   ungroup() %>%
#   group_by(app) %>%
#   mutate(diff_app=as.numeric(click_time-lag(click_time)), 
#          pct_att_app=cumsum(is_attributed)/1:n(), 
#          cps_diff_app = as.numeric(click_time-click_time[1])/1:n() ) %>%
#   ungroup() %>%
#   group_by(os) %>%
#   mutate(diff_os=as.numeric(click_time-lag(click_time)), 
#          pct_att_os=cumsum(is_attributed)/1:n(), 
#          cps_os = as.numeric(click_time-click_time[1])/1:n() ) %>% 
#   ungroup() %>% 
#   group_by(device,os) %>%
#   mutate(diff_device_os=as.numeric(click_time-lag(click_time)), 
#          pct_att_device_os=cumsum(is_attributed)/1:n(), 
#          cps_diff_device_os = as.numeric(click_time-click_time[1])/1:n() ) %>%
#   ungroup() %>% 
#   group_by(channel) %>% 
#   mutate(diff_channel=as.numeric(click_time-lag(click_time)), 
#          pct_att_channel=cumsum(is_attributed)/1:n(), 
#          cps_diff_channel = as.numeric(click_time-click_time[1])/1:n() ) %>% 
#   ungroup() %>% 
#   group_by(channel,device,os) %>%
#   mutate(diff_channel_device_os=as.numeric(click_time-lag(click_time)), 
#          pct_att_channel_device_os=cumsum(is_attributed)/1:n(), 
#          cps_diff_channel_device_os = as.numeric(click_time-click_time[1])/1:n() ) %>%
#   ungroup()  -> train_fe
# 
# train_fe %>% head(100)

```

```{r}
train %>% 
  group_by(device) %>%
  summarize( pct_att_device=sum(is_attributed)/n() ) %>%
  ungroup() -> tr_device

#save(tr_device, file="tr_device.RDS")

train %>% 
  group_by(app) %>%
  summarize( pct_att_app=sum(is_attributed)/n() ) %>%
  ungroup() -> tr_app

#save(tr_device, file="tr_device.RDS")

train %>% 
  group_by(os) %>%
  summarize(pct_att_os=sum(is_attributed)/n() ) %>% 
  ungroup() -> tr_os

#save(tr_device, file="tr_device.RDS")

train %>% 
  group_by(device,os) %>%
  summarize(pct_att_device_os=sum(is_attributed)/n() ) %>%
  ungroup() -> tr_device_os

#save(tr_device, file="tr_device.RDS")

train %>% 
  group_by(channel) %>% 
  summarize(pct_att_channel=sum(is_attributed)/n() ) %>% 
  ungroup() -> tr_channel
  
train %>% 
  group_by(channel,device,os) %>%
  summarize(pct_att_channel_device_os=sum(is_attributed)/n() ) %>%
  ungroup()  -> tr_channel_device_os

save(tr_device, tr_app, tr_os, tr_device_os, tr_channel, tr_channel_device_os, file="tr_sum_tables.RDS")

```





```{r, fig.width=14}

ggplot(tr_app %>% sample_n(10^6)) + 
  geom_line(aes(x=click_time, y=pct_att_app, group=app, color=factor(is_attributed))) 
  
```


```{r, fig.width=14}

ggplot(train_fe_red) + 
  geom_line(aes(x=click_time, y=pct_att_channel, group=channel, color=factor(channel))) 
  
```

```{r, fig.width=14}
ggplot(train_fe_red) + 
  geom_line(aes(x=click_time, y=pct_att_os, group=os, color=factor(os))) 
  
```


```{r, fig.width=14}
ggplot(train_fe %>% sample_n(10^7)) + 
  geom_histogram(aes(x=pct_att_device, fill=factor(device)), bins=100 ) + 
  scale_x_log10()

```

```{r, fig.width=14}
ggplot(train_fe_red) + 
  geom_line(aes(x=click_time, y=pct_att_device, group=device, color=factor(device)) )

```

```{r, fig.width=14}
ggplot(train_fe_red) + 
  geom_line(aes(x=click_time, y=pct_att_device_os, group=1), color="black") 

```


```{r, fig.width=14}
ggplot(train_fe_red) + 
  geom_line(aes(x=click_time, y=pct_att_channel_device_os, group=1), color="purple") 
```

```{r}
ggplot( train_fe_red ) + 
  #geom_line(aes(x=click_time, y=diff_app, group=app)) +
 # geom_line(aes(x=click_time, y=diff_channel, group=channel)) +
#  geom_line(aes(x=click_time, y=diff_os, group=os)) +
#  geom_line(aes(x=click_time, y=diff_device, group=device)) +
#  geom_line(aes(x=click_time, y=diff_device_os, group=1)) +
  geom_line(aes(x=click_time, y=diff_channel_device_os, group=1)) +
  facet_wrap(~factor(is_attributed), scale="free_x", ncol=2)
  
```

```{r}
ggplot( train_fe_red ) + 
  # geom_line(aes(x=click_time, y=cps_diff_channel, group=channel, color=factor(is_attributed))) # +
  # geom_line(aes(x=click_time, y=cps_os, group=os, color=factor(is_attributed))) #+
  geom_line(aes(x=click_time, y=cps_diff_device, group=device, color=factor(is_attributed))) #+
  # geom_line(aes(x=click_time, y=cps_diff_device_os, group=1)) #+
  # geom_line(aes(x=click_time, y=cps_diff_channel_device_os, group=1)) #+
  facet_wrap(~day, scale="free_x", ncol=2)
```


```{r}
ggplot( train_fe_red ) + 
  #geom_line(aes(x=click_time, y=cps_diff_channel, group=channel, color=factor(is_attributed))) # +
  geom_line(aes(x=click_time, y=cps_os, group=os, color=factor(is_attributed))) #+
  # geom_line(aes(x=click_time, y=cps_diff_device, group=device)) +
  # geom_line(aes(x=click_time, y=cps_diff_device_os, group=1)) +
  # geom_line(aes(x=click_time, y=cps_diff_channel_device_os, group=1)) +
  facet_wrap(~day, scale="free_x", ncol=2)
```

```{r}
ggplot( train_fe_red ) + 
  # geom_line(aes(x=click_time, y=cps_diff_channel, group=channel, color=factor(is_attributed))) 
  # geom_line(aes(x=click_time, y=cps_diff_os, group=os)) +
  # geom_line(aes(x=click_time, y=cps_diff_device, group=device)) +
  # geom_line(aes(x=click_time, y=cps_diff_device_os, group=1)) +
  geom_line(aes(x=click_time, y=cps_diff_channel_device_os, group=channel)) +
  facet_wrap(~is_attributed, scale="free_x", ncol=2)
```


```{r, fig.width=14}
ggplot( train_fe_red ) + 
  geom_line(aes(x=click_time, y=cps_diff_channel,  group=factor(channel), color=factor(channel))) + 
  geom_point(data=train_fe_red %>% filter(is_attributed==1),aes(x=click_time, y=cps_diff_channel), color="black") +
  scale_y_log10() 
  # geom_line(aes(x=click_time, y=cps_diff_os, group=os)) +
  # geom_line(aes(x=click_time, y=cps_diff_device, group=device)) +
  # geom_line(aes(x=click_time, y=cps_diff_device_os, group=1)) +
  # geom_line(aes(x=click_time, y=cps_diff_channel_device_os, group=1)) +
  facet_wrap(~is_attributed, scale="free_x", ncol=2)
```



TODO: sd in diff time

```{r}
# train %>% filter( ! is.na(diff_device) ) %>% filter( diff_device<0 ) %>% nrow()
# train %>% filter( ! is.na(diff_os) ) %>% filter( diff_os<0 ) %>% nrow()
# train %>% filter( ! is.na(diff_channel) ) %>% filter( diff_channel<0)  %>% nrow()
```

```{r}

print(n_cores<-detectCores()-1)
cluster <- create_cluster(n_cores)
print(cluster)
set_default_cluster(cluster)

```


```{r}
tr <- partition(train, ip, cluster=cluster)

#rm(train); gc()
#rm(test_sup_train)

```

```{r}

tr %>% 
  
  group_by(ip, day, device, os, channel, add=F) %>%
  mutate( pct_att_ip_device_os_channel = cumsum(is_attributed)/1:n() ) %>% 
  
  group_by(ip, day, device, os, add=F) %>%
  mutate( pct_att_ip_device_os = cumsum(is_attributed)/1:n() ) %>% 
  
  group_by(ip, day, device, add=F) %>%
  mutate( pct_att_ip_device = cumsum(is_attributed)/1:n() ) %>%
  
  group_by(ip, day, os, add=F) %>%
  mutate( pct_att_ip_os = cumsum(is_attributed)/1:n() ) %>%
  
  group_by(ip, day, add=F) %>%
  mutate( pct_att_ip = cumsum(is_attributed)/1:n() ) %>% 
  
  group_by(ip, day, device) %>%
  mutate( pct_att_device=cumsum(is_attributed)/1:n() ) %>%

  group_by(ip, day, channel) %>%
  mutate( pct_att_device=cumsum(is_attributed)/1:n() ) %>%
  
  group_by(ip, day, os) %>%
  mutate( pct_att_os=cumsum(is_attributed)/1:n() ) -> tr_ip

```


```{r}
save(tr_ip, file="tr_ip.RDS")
```


```{r}
# device, os, channel, app
# Calculate, n clicks, n downloads, pct, pct_inv

tr %>% 
  group_by(ip, day) %>% 
  summarise( n=n(), pct_att_ip = sum(is_attributed, na.rm=T) / n() ) %>% collect() -> tb_ip 

tr %>% 
  group_by(ip, day,  device) %>% 
  summarise( n=n(), pct_att_ip_device = sum(is_attributed, na.rm=T) / n()) %>% collect() -> tb_ip_device
  
tr %>%
  group_by(ip, day, os) %>%
  summarise( pct_att_ip_os = sum(is_attributed, na.rm=T) / n()) %>% collect() -> tb_ip_os

tr %>%
  group_by(ip, day, app) %>%
  summarise( n=n(), pct_att_ip_app = sum(is_attributed, na.rm=T) / n() ) %>% collect() -> tb_ip_app

tr %>%
  group_by(ip, day, channel) %>%
  summarise( n=n(), pct_att_ip_channel = sum(is_attributed, na.rm=T) / n() ) %>% collect() -> tb_ip_channel

tr %>%
  group_by(ip, day, app, channel) %>%
  summarise( n=n(), pct_att_ip_channel = sum(is_attributed, na.rm=T) / n() ) %>% collect() -> tb_ip_app_channel

tr %>% 
  group_by(ip, day, device, os) %>% 
  summarise( n=n(), pct_att_ip_device_os = sum(is_attributed, na.rm=T) / n() ) %>% collect() -> tb_ip_device_os

tr %>%
  group_by(ip, day, channel, device) %>%
  summarise( n=n(), pct_att_ip_channel_device = sum(is_attributed, na.rm=T) / n() ) %>% collect() -> tb_ip_channel_device

tr %>%
  group_by(ip, day, channel, device, os) %>%
  summarise( n=n(), pct_att_ip_channel_device_os = sum(is_attributed, na.rm=T) / n() ) %>% collect() -> tb_ip_channel_device_os

save(tb_ip, tb_ip_app, tb_ip_app_channel, 
     tb_ip_channel, tb_ip_device, tb_ip_device_os, 
     tb_ip_channel_device, tb_ip_channel_device_os, tb_ip_os, file="tr_ip_sum_tables.RDS")

```


