---
title: "R Notebook"
output: html_notebook
---

```{r}
source("utils_BuildDS.R")
```


```{r}
load("test.csv.RDS")
```


```{r}
test %<>% mutate(day=format(click_time,"%d"), hour=as.numeric(format(click_time,"%H") ))

load("tr_sum_tables.RDS")
test %<>% zero_set()
```


```{r}
rm(tr_app, tr_channel, tr_os, tr_device, tr_channel_device_os, tr_device_app, tr_device_os)
load("tr_ip_sum_tables.RDS")
test %<>% first_set()
```


```{r}
rm(tb_ip, tb_ip_app, tb_ip_channel, tb_ip_os, tb_ip_device)
load("tr_ip_sum_comb_tables.RDS")
test %<>% second_set()
```


```{r}
rm(tb_ip_app_channel, tb_ip_channel_device, tb_ip_device_os)
load("tr_ip_sum_4_tables.RDS")
test %<>% third_set()
test %>% head(100)
```


```{r}
test %<>% adjust_set()
```


```{r}
test %<>% mutate(is_attributed=factor(0))
test %<>% select(-click_time, -day)

testTask <- makeClassifTask(data=test , target = "is_attributed" )
```


```{r}
# Make a new prediction
result <- predict(xgb_model, testTask)
prediction <- result$data %>% select(click_id = id, is_attributed = response) 

write_csv(prediction, "final_prediction.csv")
```

