---
title: "R Notebook"
output: html_notebook
---

```{r}
library(pacman)
p_load(ggplot2) # Data visualization
p_load(readr) # CSV file I/O, e.g. the read_csv function
p_load(dplyr)
library(multidplyr)
p_load(parallel)
p_load(fasttime)
p_load(xgboost)
p_load(mlr)
p_load(mlrMBO)
p_load(caret)
p_load(magrittr)
p_load(parallelMap)
p_load(DiceKriging)
p_load(rgenoud)


# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory
#devtools::install_github("hadley/multidplyr")
```

```{r}
print(n_cores<-detectCores()-1)
```

# load data

```{r}
train <- read_csv("train_sample.csv", progress=T)
train %>% nrow()
```
```{r}
train %>% head(100)
```


```{r}
train %>% colnames()
```

```{r}
table(train$is_attributed)
```

```{r}
retype <- function(df){
  df %>% mutate(ip=as.numeric(ip), 
                 app=as.numeric(app), 
                 device=as.numeric(device), 
                 os=as.numeric(os), 
                 channel=as.numeric(channel))
}

train %<>% retype()

```


# train, validation and test

```{r}
VAL_TIME <- "2017-11-09 04:"
TR_TIME <- "2017-11-07 14:"

valid_cv <- train %>% filter(click_time>= VAL_TIME)

tr_neg <- train %>% filter(click_time < VAL_TIME & click_time >= TR_TIME & is_attributed==0)
tr_pos <- train %>% filter(click_time < VAL_TIME & is_attributed==1)
```

```{r}
table(valid_cv$is_attributed)
```

```{r}
table(tr_neg$is_attributed)
```

```{r}
table(tr_pos$is_attributed)
```

```{r}
tr_neg %<>% mutate(ct=fasttime::fastPOSIXct(click_time), cth=substring(click_time,1,13)) 
tr_neg %>% head(100)
```

```{r}
table(tr_neg$cth)
```

```{r}
times <- 5
pct <- 1 - 1/5
set.seed(0)

tr_pt <-createDataPartition(tr_neg$cth, times = times, p = pct, list=F)
tr_pt %>%  head(20)
```


```{r}
params <- getParamSet("classif.xgboost")
params
```

```{r}
xgb_param <- makeParamSet(
  makeIntegerParam("max_depth", lower = 1, upper = 10),  # number of splits in each tree
  makeNumericParam("eta", lower = .1, upper = .8), # "shrinkage" - prevents overfitting
  makeNumericParam("lambda", lower = -1, upper = 0, trafo = function(x) 10^x) # L2 regularization - prevents overfitting
)
```

```{r}
# mlrMBO part
mboControl <- makeMBOControl()
mboControl <- setMBOControlTermination(mboControl, iters = 15)  # in addition to the initials
mboControl <- setMBOControlInfill(mboControl, crit = makeMBOInfillCritAEI()) # augmented expected improvement
# mlr part
tuneMBOControl <- makeTuneControlMBO(mbo.control = mboControl)
```

```{r}
tr_neg %<>% select(-ct,-cth)
```


## Dynamic setup

```{r}
i <- 1
indexes <- tr_pt[,paste0("Resample",i)]
train_cv <- rbind(tr_neg[indexes,], tr_pos)
```


```{r}

train_cv_matrix <- xgboost::xgb.DMatrix(data=data.matrix(train_cv %>% select(-is_attributed)),
                                        label=train_cv$is_attributed)
valid_cv_matrix <- xgboost::xgb.DMatrix(data=data.matrix(valid_cv %>% select(-is_attributed)),
                                        label=valid_cv$is_attributed)

xgb <- makeLearner( "classif.xgboost", 
                    predict.type = "prob",
                    par.vals = list(
                      objective = "binary:logistic",
                      eval_metric = "auc",
                      watchlist = list( train = train_cv_matrix, val = valid_cv_matrix),
                      nrounds = 200, 
                      maximize = T,
                      verbose = 1, 
                      print_every_n = 5,
                      early_stopping_rounds = 5)
                    )

```

```{r}
train_cv %<>% select(-click_time, -attributed_time)
```

```{r}
#control <- makeTuneControlRandom(maxit = 10)
```


```{r}

trainTask <- makeClassifTask(data = train_cv, target = "is_attributed", positive = 1)

resTune <- tuneParams(learner=xgb, 
                task=trainTask, 
                resampling=makeResampleDesc("Subsample", iters = 2, split = 0.95),
                # TODO: PROVIDE resample.fun
                measures=auc, 
                par.set = xgb_param, 
                control = tuneMBOControl, 
                show.info = F)
```

```{r}

```

```{r}

```


```{r}

```

 