---
title: "R Notebook"
output: html_notebook
---

```{r}
library(pacman)
p_load(ggplot2) # Data visualization
p_load(readr) # CSV file I/O, e.g. the read_csv function
p_load(dplyr)
library(multidplyr)
p_load(parallel)
p_load(fasttime)
p_load(xgboost)
p_load(parallel)
p_load(magrittr)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory
#devtools::install_github("hadley/multidplyr")
```

```{r}
source("utils_EDA.R")
```

# Load Data

```{r}

load("train.csv.RDS")
#load("test_sup_train.Rds")

```

# join the two datasets

# Feature Engineering

TODO: window of 1hr, 4hr, 12hr, ...
TODO: add test_supp to train n calculations
TODO: explore hour variability
TODO: some features must be created on test directly (not copied from train data)
TODO: deal with NA's, in test mainly
TODO: increase training size
TODO: add NB feature

```{r}
train %<>% mutate(id=1:n(), day=format(click_time,"%d"), hour=as.numeric(format(click_time,"%H") ))

train %>% head(100)
```


```{r}
# train %>% 
#   group_by(device) %>%
#   mutate(diff_device=as.numeric(click_time-lag(click_time)), 
#          pct_att_device=cumsum(is_attributed)/1:n(), 
#          cps_diff_device = as.numeric(click_time-click_time[1])/1:n() ) %>%
#   ungroup() %>%
#   group_by(app) %>%
#   mutate(diff_app=as.numeric(click_time-lag(click_time)), 
#          pct_att_app=cumsum(is_attributed)/1:n(), 
#          cps_diff_app = as.numeric(click_time-click_time[1])/1:n() ) %>%
#   ungroup() %>%
#   group_by(os) %>%
#   mutate(diff_os=as.numeric(click_time-lag(click_time)), 
#          pct_att_os=cumsum(is_attributed)/1:n(), 
#          cps_os = as.numeric(click_time-click_time[1])/1:n() ) %>% 
#   ungroup() %>% 
#   group_by(device,os) %>%
#   mutate(diff_device_os=as.numeric(click_time-lag(click_time)), 
#          pct_att_device_os=cumsum(is_attributed)/1:n(), 
#          cps_diff_device_os = as.numeric(click_time-click_time[1])/1:n() ) %>%
#   ungroup() %>% 
#   group_by(channel) %>% 
#   mutate(diff_channel=as.numeric(click_time-lag(click_time)), 
#          pct_att_channel=cumsum(is_attributed)/1:n(), 
#          cps_diff_channel = as.numeric(click_time-click_time[1])/1:n() ) %>% 
#   ungroup() %>% 
#   group_by(channel,device,os) %>%
#   mutate(diff_channel_device_os=as.numeric(click_time-lag(click_time)), 
#          pct_att_channel_device_os=cumsum(is_attributed)/1:n(), 
#          cps_diff_channel_device_os = as.numeric(click_time-click_time[1])/1:n() ) %>%
#   ungroup()  -> train_fe
# 
# train_fe %>% head(100)

```

```{r}
train %>% 
  group_by(device) %>%
  summarize( pct_att_device=log((sum(is_attributed)+1)/(n()+1)), n_device=n() ) %>%
  ungroup() -> tr_device

train %>% 
  group_by(app) %>%
  summarize( pct_att_app=log((sum(is_attributed)+1)/(n()+1)), n_app=n() ) %>%
  ungroup() -> tr_app

train %>% 
  group_by(os) %>%
  summarize(pct_att_os=log((sum(is_attributed)+1)/(n()+1)), n_os=n() ) %>% 
  ungroup() -> tr_os


train %>% 
  group_by(device,os) %>%
  summarize(pct_att_device_os=log((sum(is_attributed)+1)/(n()+1)), n_device_os=n() ) %>%
  ungroup() -> tr_device_os

train %>% 
  group_by(device,app) %>%
  summarize(pct_att_device_app=log((sum(is_attributed)+1)/(n()+1)), n_device_app=n() ) %>%
  ungroup() -> tr_device_app

train %>% 
  group_by(channel) %>% 
  summarize(pct_att_channel=log((sum(is_attributed)+1)/(n()+1)), n_channel=n() ) %>% 
  ungroup() -> tr_channel
  
train %>% 
  group_by(channel,device,os) %>%
  summarize(pct_att_channel_device_os=log((sum(is_attributed)+1)/(n()+1)), n_channel_device_os=n() ) %>%
  ungroup()  -> tr_channel_device_os


```

```{r, fig.width=14}

ggplot(tr_app ) + 
  geom_point(aes(x=n_app, y=pct_att_app, color=factor(app))) + 
  scale_x_log10() +
  theme(legend.position = "none")
  
```

```{r, fig.width=14}

ggplot(tr_os ) + 
  geom_point(aes(x=n_os, y=pct_att_os, color=factor(os))) +  
  scale_x_log10() +
  theme(legend.position = "none")

```


```{r, fig.width=14}

ggplot(tr_channel) + 
  geom_point(aes(x=n_channel, y=pct_att_channel, color=factor(channel))) + 
  scale_x_log10()+
  theme(legend.position = "none")

  
```


```{r, fig.width=14}

ggplot(tr_device_app ) + 
  geom_point(aes(x=n_device_app, y=pct_att_device_app, color=factor(device))) +
  scale_x_log10() +
  theme(legend.position = "none")
  
```

```{r, fig.width=14}

ggplot(tr_device ) + 
  geom_point(aes(x=n_device, y=pct_att_device, color=factor(device))) +
  scale_x_log10() +
  theme(legend.position = "none")
  
```

```{r, fig.width=14}

ggplot(tr_channel_device_os ) + 
  geom_point(aes(x=n_channel_device_os, y=pct_att_channel_device_os, color=factor(channel))) +
  scale_x_log10() +
  theme(legend.position = "none")
  
```

```{r}
save(tr_device, tr_app, tr_os, tr_device_os, tr_channel, tr_device_app, tr_channel_device_os, file="tr_sum_tables.RDS")
rm(tr_device, tr_app, tr_os, tr_device_os, tr_device_app, tr_channel, tr_channel_device_os);gc()
```


```{r}
# train %>% filter( ! is.na(diff_device) ) %>% filter( diff_device<0 ) %>% nrow()
# train %>% filter( ! is.na(diff_os) ) %>% filter( diff_os<0 ) %>% nrow()
# train %>% filter( ! is.na(diff_channel) ) %>% filter( diff_channel<0)  %>% nrow()

```

No negative diffs, the order is preserved

```{r}

print(n_cores <- detectCores()-1)
cluster <- create_cluster(n_cores)
print(cluster)
set_default_cluster(cluster)

```


```{r}
tr <- partition(train, ip, cluster=cluster)

rm(train); gc()
#rm(test_sup_train)

```

```{r}

# tr %>% 
#   
#   group_by(ip, day, device, os, channel, add=F) %>%
#   mutate( pct_att_ip_device_os_channel = cumsum(is_attributed)/1:n() ) %>% 
#   
#   group_by(ip, day, device, os, add=F) %>%
#   mutate( pct_att_ip_device_os = cumsum(is_attributed)/1:n() ) %>% 
#   
#   group_by(ip, day, device, add=F) %>%
#   mutate( pct_att_ip_device = cumsum(is_attributed)/1:n() ) %>%
#   
#   group_by(ip, day, os, add=F) %>%
#   mutate( pct_att_ip_os = cumsum(is_attributed)/1:n() ) %>%
#   
#   group_by(ip, day, add=F) %>%
#   mutate( pct_att_ip = cumsum(is_attributed)/1:n() ) %>% 
#   
#   group_by(ip, day, device) %>%
#   mutate( pct_att_device=cumsum(is_attributed)/1:n() ) %>%
# 
#   group_by(ip, day, channel) %>%
#   mutate( pct_att_device=cumsum(is_attributed)/1:n() ) %>%
#   
#   group_by(ip, day, os) %>%
#   mutate( pct_att_os=cumsum(is_attributed)/1:n() ) -> tr_ip
# save(tr_ip, file="tr_ip.RDS")
```

```{r}
# device, os, channel, app
# Calculate, n clicks, n downloads, pct, pct_inv

# tr %>% 
#   group_by(ip, day) %>% 
#   summarise( n_ip=n(), pct_att_ip = log((sum(is_attributed)+1)/(n()+1)) ) %>% collect() -> tb_ip 
# 
# tr %>% 
#   group_by(ip, day,  device) %>% 
#   summarise( n_ip_dev=n(), pct_att_ip_device = log((sum(is_attributed)+1)/(n()+1))) %>% collect() -> tb_ip_device
#   
# tr %>%
#   group_by(ip, day, os) %>%
#   summarise( n_ip_os=n(), pct_att_ip_os = log((sum(is_attributed)+1)/(n()+1))) %>% collect() -> tb_ip_os
# 
# tr %>%
#   group_by(ip, day, app) %>%
#   summarise( n_ip_app=n(), pct_att_ip_app = log((sum(is_attributed)+1)/(n()+1))) %>% collect() -> tb_ip_app
# 
# tr %>%
#   group_by(ip, day, channel) %>%
#   summarise( n_ip_channel=n(), pct_att_ip_channel = log((sum(is_attributed)+1)/(n()+1)) ) %>% collect() -> tb_ip_channel
# 
# save(tb_ip, tb_ip_app, tb_ip_channel, tb_ip_device, tb_ip_os, file="tr_ip_sum_tables.RDS")
# #rm(tb_ip, tb_ip_app, tb_ip_channel, tb_ip_device, tb_ip_os)

```

```{r}

# tr %>%
#   group_by(ip, day, app, channel) %>%
#   summarise( n=n(), pct_att_ip_channel = log((sum(is_attributed)+1)/(n()+1)) ) %>% collect() -> tb_ip_app_channel
# 
# tr %>% 
#   group_by(ip, day, device, os) %>% 
#   summarise( n=n(), pct_att_ip_device_os = log((sum(is_attributed)+1)/(n()+1)) ) %>% collect() -> tb_ip_device_os
# 
# tr %>%
#   group_by(ip, day, channel, device) %>%
#   summarise( n=n(), pct_att_ip_channel_device = log((sum(is_attributed)+1)/(n()+1)) ) %>% collect() -> tb_ip_channel_device
# 
# save(tb_ip_app_channel, tb_ip_device_os, tb_ip_channel_device, file="tr_ip_sum_comb_tables.RDS")
# #rm(tb_ip_app_channel, tb_ip_device_os, tb_ip_channel_device)

```

```{r}

# tr %>%
#   group_by(ip, day, channel, device, os) %>%
#   mutate(diff=click_time-lag(click_time)) %>% 
#   summarise( n=n(), pct_att_ip_channel_device_os = log((sum(is_attributed)+1)/(n()+1)), 
#              diff_sd = sd(diff, na.rm=T), diff_mean = mean(diff, na.rm=T) ) %>% collect() -> tb_ip_channel_device_os
# 
# save( tb_ip_channel_device_os, file="tr_ip_sum_4_tables.RDS")
# #rm(tb_ip_channel_device_os)

```


```{r}
# device, os, channel, app
# Calculate, n clicks, n downloads, pct, pct_inv

tr %>% 
  group_by(ip) %>% 
  summarise( n_ip=n(), pct_att_ip = log((sum(is_attributed)+1)/(n()+1)) ) %>% collect() -> tb_ip 

tr %>% 
  group_by(ip, device) %>% 
  summarise( n_ip_dev=n(), pct_att_ip_device = log((sum(is_attributed)+1)/(n()+1))) %>% collect() -> tb_ip_device
  
tr %>%
  group_by(ip, os) %>%
  summarise( n_ip_os=n(), pct_att_ip_os = log((sum(is_attributed)+1)/(n()+1))) %>% collect() -> tb_ip_os

tr %>%
  group_by(ip, app) %>%
  summarise( n_ip_app=n(), pct_att_ip_app = log((sum(is_attributed)+1)/(n()+1))) %>% collect() -> tb_ip_app

tr %>%
  group_by(ip, channel) %>%
  summarise( n_ip_channel=n(), pct_att_ip_channel = log((sum(is_attributed)+1)/(n()+1)) ) %>% collect() -> tb_ip_channel

save(tb_ip, tb_ip_app, tb_ip_channel, tb_ip_device, tb_ip_os, file="tr_ip_sum_tables.RDS")
#rm(tb_ip, tb_ip_app, tb_ip_channel, tb_ip_device, tb_ip_os)

```

```{r}

tr %>%
  group_by(ip, app, channel) %>%
  summarise( n_ip_app_channel=n(), pct_att_ip_channel = log((sum(is_attributed)+1)/(n()+1)) ) %>% collect() -> tb_ip_app_channel

tr %>% 
  group_by(ip, device, os) %>% 
  summarise( n_ip_device_os=n(), pct_att_ip_device_os = log((sum(is_attributed)+1)/(n()+1)) ) %>% collect() -> tb_ip_device_os

tr %>%
  group_by(ip, channel, device) %>%
  summarise( n_ip_channel_device=n(), pct_att_ip_channel_device = log((sum(is_attributed)+1)/(n()+1)) ) %>% collect() -> tb_ip_channel_device

save(tb_ip_app_channel, tb_ip_device_os, tb_ip_channel_device, file="tr_ip_sum_comb_tables.RDS")
#rm(tb_ip_app_channel, tb_ip_device_os, tb_ip_channel_device)

```

```{r}

tr %>%
  group_by(ip, channel, device, os) %>%
  mutate(diff=click_time-lag(click_time)) %>% 
  summarise( n_ip_c_d_os=n(), pct_att_ip_channel_device_os = log((sum(is_attributed)+1)/(n()+1)), 
             diff_sd = sd(diff, na.rm=T), diff_mean = mean(diff, na.rm=T) ) %>% collect() -> tb_ip_channel_device_os

save( tb_ip_channel_device_os, file="tr_ip_sum_4_tables.RDS")
#rm(tb_ip_channel_device_os)

```



```{r}
# tb_ip_channel_device_os %>% sample_frac(0.0001) -> tb_ip_channel_device_os_red
tb_ip_channel_device_os[1:100000,] -> tb_ip_channel_device_os_red

ggplot(tb_ip_channel_device_os_red) + geom_point(aes(y=pct_att_ip_channel_device_os,x=diff_sd,color=n)) + scale_x_log10() 
```

